#!/bin/bash
# COMANDOS ÚTEIS - NR1 EAD
# Copie e cole os comandos conforme necessário

echo "📋 COMANDOS ÚTEIS - NR1 EAD"
echo "══════════════════════════════════════════════════════════"
echo ""

# ============================================================
# SETUP INICIAL
# ============================================================
echo "🚀 SETUP INICIAL"
echo "──────────────────────────────────────────────────────────"
echo ""
echo "1️⃣  Setup Automático (Linux/Mac):"
echo "    bash setup.sh"
echo ""
echo "2️⃣  Setup Automático (Windows):"
echo "    setup.bat"
echo ""
echo "3️⃣  Manual - Backend:"
echo "    cd backend"
echo "    npm install"
echo "    cp .env.example .env"
echo "    npm run migrate"
echo "    npm run dev"
echo ""
echo "4️⃣  Manual - Frontend:"
echo "    cd frontend"
echo "    npm install"
echo "    npm run dev"
echo ""

# ============================================================
# DESENVOLVIMENTO
# ============================================================
echo "💻 DESENVOLVIMENTO"
echo "──────────────────────────────────────────────────────────"
echo ""
echo "Backend (modo dev com auto-reload):"
echo "    cd backend && npm run dev"
echo ""
echo "Frontend (modo dev com Vite):"
echo "    cd frontend && npm run dev"
echo ""
echo "Build Frontend para produção:"
echo "    cd frontend && npm run build"
echo ""

# ============================================================
# BANCO DE DADOS
# ============================================================
echo "🗄️  BANCO DE DADOS"
echo "──────────────────────────────────────────────────────────"
echo ""
echo "Criar tabelas:"
echo "    cd backend && npm run migrate"
echo ""
echo "Conectar ao MySQL:"
echo "    mysql -h localhost -u root -p"
echo ""
echo "Ver bancos de dados:"
echo "    SHOW DATABASES;"
echo ""
echo "Usar banco nr1_ead:"
echo "    USE nr1_ead;"
echo ""
echo "Ver todas as tabelas:"
echo "    SHOW TABLES;"
echo ""
echo "Ver estrutura de uma tabela:"
echo "    DESCRIBE usuarios;"
echo ""
echo "Fazer backup:"
echo "    mysqldump -u root -p nr1_ead > backup.sql"
echo ""
echo "Restaurar backup:"
echo "    mysql -u root -p nr1_ead < backup.sql"
echo ""

# ============================================================
# TESTES DE API
# ============================================================
echo "🧪 TESTES DE API"
echo "──────────────────────────────────────────────────────────"
echo ""
echo "Health Check:"
echo "    curl http://localhost:5000/health"
echo ""
echo "Registrar usuário:"
echo "    curl -X POST http://localhost:5000/api/auth/register \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"nome\":\"Teste\",\"email\":\"teste@example.com\",\"senha\":\"123456\"}'"
echo ""
echo "Fazer login:"
echo "    curl -X POST http://localhost:5000/api/auth/login \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"email\":\"teste@example.com\",\"senha\":\"123456\"}'"
echo ""
echo "Listar usuários (admin):"
echo "    curl -X GET http://localhost:5000/api/usuarios \\"
echo "      -H 'Authorization: Bearer SEU_TOKEN'"
echo ""

# ============================================================
# TROUBLESHOOTING
# ============================================================
echo "🔧 TROUBLESHOOTING"
echo "──────────────────────────────────────────────────────────"
echo ""
echo "Porta 5000 já em uso:"
echo "    macOS/Linux:"
echo "        lsof -i :5000"
echo "        kill -9 <PID>"
echo ""
echo "    Windows:"
echo "        netstat -ano | findstr :5000"
echo "        taskkill /PID <PID> /F"
echo ""
echo "Limpar node_modules:"
echo "    rm -rf backend/node_modules frontend/node_modules"
echo "    npm install (em cada pasta)"
echo ""
echo "Limpar localStorage (navegador):"
echo "    localStorage.clear()"
echo ""
echo "Ver logs do servidor:"
echo "    tail -f backend/logs/*.log"
echo ""

# ============================================================
# PRODUÇÃO
# ============================================================
echo "🚀 PRODUÇÃO"
echo "──────────────────────────────────────────────────────────"
echo ""
echo "Instalar dependências:"
echo "    npm install --production"
echo ""
echo "Build Frontend:"
echo "    npm run build"
echo ""
echo "Iniciar Backend em produção:"
echo "    NODE_ENV=production npm start"
echo ""
echo "Usar PM2 para gerenciar processo:"
echo "    npm install -g pm2"
echo "    pm2 start src/index.js --name 'nr1-backend'"
echo "    pm2 save"
echo "    pm2 startup"
echo ""

# ============================================================
# DOCKER
# ============================================================
echo "🐳 DOCKER"
echo "──────────────────────────────────────────────────────────"
echo ""
echo "Iniciar MySQL com Docker Compose:"
echo "    docker-compose up -d"
echo ""
echo "Parar containers:"
echo "    docker-compose down"
echo ""
echo "Ver logs:"
echo "    docker-compose logs -f"
echo ""

# ============================================================
# UTILIDADE
# ============================================================
echo "🛠️  UTILIDADE"
echo "──────────────────────────────────────────────────────────"
echo ""
echo "Verificar versões:"
echo "    node --version"
echo "    npm --version"
echo "    mysql --version"
echo ""
echo "Instalar dependências globais:"
echo "    npm install -g nodemon"
echo "    npm install -g pm2"
echo ""
echo "Atualizar npm:"
echo "    npm install -g npm@latest"
echo ""

echo ""
echo "══════════════════════════════════════════════════════════"
echo "✅ Mais informações em SETUP.md e docs/API.md"
echo "══════════════════════════════════════════════════════════"
